FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /backend

# Copy the current directory contents into the container at /backend
COPY ./backend /backend

# Install dependencies
RUN apt update && apt install -y python3-dev default-libmysqlclient-dev build-essential pkg-config && \
    python -m venv /py && \
    /py/bin/pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

# Expose port 8000
EXPOSE 8000

# Define the command to run the app
CMD ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]
